name: Test
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
          run: yarn test
